name: Issue Template
description: Template for creating issues
body:
  - type: markdown
    attributes:
      value: |
        ## Issue Template

        Please fill out the following information when creating a new issue.

        ### Description

        [Description of the issue]

        ### Steps to Reproduce

        [Steps to reproduce the issue]

        ### Expected Behavior

        [What you expected to happen]

        ### Actual Behavior

        [What actually happened]

        ### Additional Information

        [Any additional information that may be helpful]

