name: rtl_433_discovery
version: "0.0.2"
slug: rtl433hadiscovery
description: rtl_433 for Home Assistant
url: "https://github.com/catduckgnaf/rtl_433_ha/tree/main/rtl_433_mqtt_autodiscovery"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
startup: application
services:
  - mqtt:want
usb: true
udev: true
ports:
  8000/tcp: 8000
map:
  - share:rw
  - config:rw
options:
  mqtt_host: ""
  mqtt_port: 1883
  mqtt_user: ""
  mqtt_password: ""
  retain: true
  rtl_433_config: "config/rtl_433.conf"
  rtl_topic: "rtl_433/+/events"
  discovery_prefix: "homeassistant"
  discovery_interval: 600
  force_update: false
  log_level: "default"
schema:
  mqtt_host: str
  mqtt_port: int
  mqtt_user: str
  mqtt_password: str
  retain: bool
  rtl_433_config: str
  rtl_topic: str
  discovery_prefix: str
  discovery_interval: int
  force_update: bool
  log_level: str

  # image

